import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google"
import Formulario from '../components/Formulario/Formulario'

import Header from '../components/Header/Header'
import Footer from '../components/Footer/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["300", "400", "700", "900"],
})

export const metadata: Metadata = {
  title: "Parque Olho D'Água",
  description: "Generated by create next app",
  verification: {
    google: "TAr87LJg2jH33NTLD_nTee0EEoX5nNmu6A4Rkc3Px40",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-br"
      className={`${geistSans.variable} ${geistMono.variable} w-full antialiased`}
    >
      <body className={`${roboto.className} w-full min-h-screen`}>
        <Header />
        {children}
        <Formulario />
        <Footer />
      </body>
    </html>
  );
}
